### PR TITLE
Move custom CLogger changes to struqtur-legacy

### PR DESCRIPTION
**Pull request by fredx30**
### Description

These changes are added as a separate logrouter in struqturlegacy.

### Issue 
[ch4452]
[ch493]

### CODE REVIEW

**Comment by batista** [comment]
to add to the comment above, you first place your `HEAD` on this commit, then rollback one level, keeping the changes in `stage`.

so:
```shell
git reset --hard fredx30:patch-1 && \
git reset HEAD~1 && \
git commit --fixup=fcb9a4d8b882bb52d2b06a8d4342c061d5e8b8ca
```

**Comment by fredx30** [comment]
> with this, do we fully revert this function to yii's original state?
> or are there still stuff pending in `log()`?

Yes this is a full revert for this file.

**Comment by fredx30** [comment]
I dont know how i managed this but this "branch" does not appear to actually exist. It might be something else.

**Comment by fredx30** [comment]
> i saw we added this in a commit from marten, just in this repo can you do a
> `git commit --fixup=fcb9a4d8b882bb52d2b06a8d4342c061d5e8b8ca` instead? (don't rebase with `autosquash` though.)

This is fixed now.

**Comment by fredx30** [comment]
@batista / @effata / @marten-nilsson I cant merge this myself (no access). Can one of you do it?

**Pull request merged**
